remote_theme: pages-themes/minimal@v0.2.0
  
plugins:
- jekyll-remote-theme 

  
title: "Glottography tutorials"
description: 
    From a language map image to a Glottography dataset in five steps<br><br>
  <a href="/">Home</a><br>
  <a href="/chapter1">Chapter 1</a><br>
  <a href="/chapter2">Chapter 2</a><br>
  <a href="https://github.com/username/repo">GitHub Repo</a>
  
