title: ""               # no site title
description: ""         # no tagline
theme: minima           # or whatever theme you chose

# Tell Jekyll to include our custom CSS
include:
  - assets/css/custom.css
